import os

# --- CONFIGURATION ---
IGNORE_DIRS = {
    "node_modules", ".git", ".next", "__pycache__", "venv", ".venv", ".idea", ".vscode"
}

INCLUDE_EXTENSIONS = {".ts", ".tsx", ".py", ".json", ".css"}

# Priority Files (The "Laws")
PRIORITY_FILES = [
    "CONTEXT_BRAIN.md",
    "AGENCY_MANIFEST.md",
    "UX_LEDGER.md",
    "SCAR_TISSUE.md",
    "FEATURES.md",
    "src/types/vibe-core.ts",
    "src/types/design-system.ts"
]

# Specific files to ALWAYS dump (Core Logic)
CORE_FILES = [
    "src/app/project/[id]/page.tsx",
    "src/store/vibe-store.ts",
    "src/components/WireframeNodes.tsx",
    "src/components/FlowNodes.tsx",
    "src/components/SitemapNodes.tsx",
    # We also want to capture the Backend Architect if it exists relative to us, 
    # but since it's in a different repo, we focus on the Frontend Integration points here.
]

OUTPUT_FILE = "CURRENT_STATE.txt"

def get_tree_structure(startpath):
    """Generates a visual tree of the project structure."""
    tree_str = "PROJECT STRUCTURE:\n"
    for root, dirs, files in os.walk(startpath):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        tree_str += f"{indent}{os.path.basename(root)}/\n"
        subindent = ' ' * 4 * (level + 1)
        for f in files:
            if any(f.endswith(ext) for ext in INCLUDE_EXTENSIONS) or f.endswith(".md"):
                tree_str += f"{subindent}{f}\n"
    return tree_str + "\n" + ("="*50) + "\n"

def read_file_content(filepath):
    """Reads a file and wraps it in a clear delimiter."""
    if not os.path.exists(filepath):
        return f"\n[WARNING: File not found: {filepath}]\n"
    
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
            ext = os.path.splitext(filepath)[1]
            return f"\n\n--- START OF FILE: {filepath} ---\n```{ext[1:]}\n{content}\n```\n--- END OF FILE ---\n"
    except Exception as e:
        return f"\n[Error reading {filepath}: {e}]\n"

def main():
    final_output = "CONTEXT DUMP (For AI Assistant)\n"
    final_output += "Generated by: generate_context.py\n"
    final_output += "="*50 + "\n\n"

    print("Mapping Project Structure...")
    final_output += get_tree_structure(os.getcwd())

    print("Bundling Ledgers & Contracts...")
    for f in PRIORITY_FILES:
        final_output += read_file_content(f)

    print("Bundling Core Code...")
    for f in CORE_FILES:
        if f not in PRIORITY_FILES:
            final_output += read_file_content(f)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(final_output)

    print(f"\n✅ SUCCESS! Context saved to: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()